
/*
 * MeSQL - Interpreter - interpreter.cpp
 * 
 * This file implements the class Interpreter.
 * 
 */

#include <iostream>
#include "scanner.hpp" // generated by flex
#include "parser.hpp" // generated by bison
#include "interpreter.hpp"

using namespace std;

const static char prompt_str_1[] = ">>> ";
const static char prompt_str_2[] = "... ";

namespace MeInt {

    // implement class Interpreter
    Interpreter::Interpreter() : do_prompt(true),os(&cout),m_scanner(*this),m_parser(m_scanner,*this),m_location(0) {
        setIstream(&cin);
    }
    Interpreter::Interpreter(istream *_is,ostream *_os,bool _do_prompt) : 
		do_prompt(_do_prompt),os(_os),m_scanner(*this),m_parser(m_scanner,*this),m_location(0) {
        setIstream(_is);
    }
    loc_type Interpreter::location() const {
        return m_location;
    }
    void Interpreter::increaseLocation(loc_type det) {
        m_location += det;
    }
    void Interpreter::clear() {
        m_location = 0;
    }
    void Interpreter::parse() {
        clear();
        m_parser.parse();
    }
    void Interpreter::setIstream(istream *is) {
        m_scanner.switch_streams(is,NULL);
    }
    void Interpreter::prompt() const {
        if (do_prompt) *os << prompt_str_1;
    }

}