/*
 * MeSQL - Interpreter - interpreter.hpp
 * 
 * This file declares the class Interpreter, which encapsulates
 * the flex scanner and bison parser. The class Interpreter provides
 * the final interpreter api.
 * 
 */

#ifndef INTERPRETER_HPP
#define INTERPRETER_HPP

#include <iostream>
#include "parser.hpp" // generated by bison
#include "scanner.hpp" // generated by flex
#include "../base/manager.hpp"

using namespace std;
using namespace MeMan;

typedef unsigned int loc_type;

namespace MeInt {
    class Interpreter {
    private:
        Scanner m_scanner;
        Parser m_parser;
		Manager &m_man;
        loc_type m_location;

        loc_type location() const;
        void increaseLocation(loc_type det);
    public:
        bool do_prompt;
        ostream *os;
		int state;
        Interpreter(istream *_is,ostream *_os,bool _do_prompt,Manager &_man);
        void clear();
        void parse();
        void setIstream(istream *is);
		void set_state(int _state);
        void prompt() const;
        friend class Scanner;
        friend class Parser;
    };
}

#endif