/*
 * MeSQL - Interpreter - interpreter.hpp
 * 
 * This file declares the class Interpreter, which encapsulates
 * the flex scanner and bison parser. The class Interpreter provides
 * the final interpreter api.
 * 
 */

#ifndef INTERPRETER_HPP
#define INTERPRETER_HPP

#include <iostream>
#include "scanner.hpp" // generated by flex
#include "parser.hpp" // generated by bison

using namespace std;

typedef unsigned int loc_type;

namespace MeInt {
    class Interpreter {
    private:
        Scanner m_scanner;
        Parser m_parser;
        loc_type m_location;

        loc_type location() const;
        void increaseLocation(loc_type det);
    public:
        bool do_prompt;
        ostream *os;
        Interpreter();
        Interpreter(istream *_is,ostream *_os,bool _do_prompt);
        void clear();
        void parse();
        void setIstream(istream *is);
        void prompt() const;
        friend class Scanner;
        friend class Parser;
    };
}

#endif